site_name: NEORICALEX
nav:
    - Home: 'index.md'
    - 'COPED':
        - 'README': 'coped/README.md'
    - Sobre:
        - 'Licença': 'license.md'
        - 'README': 'README.md'
theme: readthedocs
