#!/bin/bash

echo "Olá $USER tudo bem?"
echo "Eu sou o Ricardo Lourenço (Neo), Desenvolvedor e Maintainer do NEORICALEX"
echo "Desde já o meu muito obrigado por testar tanto o NEORICALEX, quanto indiretamente o meu \"filhinho\" chamado NFDOS :-)"


echo "Vou começar por checkar qual é a distribuição Linux que o $HOSTNAME está executando."
echo "Aguarde 10 segundinhos por favor ..."
sleep 7
# REF: https://stackoverflow.com/questions/29581754/how-to-find-linux-distribution-name-using-shell-script
UNAME=$(uname | tr "[:upper:]" "[:lower:]")
if [ "$UNAME" == "linux" ]; then
    if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
        DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
    else
        DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
    fi
fi
[ "$DISTRO" == "" ] && export DISTRO=$UNAME
unset UNAME

if [ "$DISTRO" == "Ubuntu" ]; then
    echo "Aparentemente o $HOSTNAME está rodando o $DISTRO. Tudo OK então :-)"
else
    echo "Aparentemente o $HOSTNAME não está rodando no Ubuntu. O $USER tem o apt instalado?"
    echo "# TODO: Checkar se o USER tem o APT instalado."
    sleep 3
fi
unset DISTRO

echo "Atualizar os repositórios e atualizar o $HOSTNAME..."
sudo apt update && sudo apt upgrade -y

echo "Instalar os requerimentos.."
sudo apt install -y \
    binutils \
    debootstrap \
    squashfs-tools \
    xorriso \
    grub-pc-bin \
    grub-efi-amd64-bin \
    mtools \
    libosinfo-bin \
    vagrant \
    vagrant-libvirt \
    vagrant-mutate

echo "Setar variáveis de ambiente..."
export NEORICALEX_HOME=$(pwd)
export NFDOS_HOME=$NEORICALEX_HOME/dev/nfdos

cd $NFDOS_HOME

vagrant up --provider=libvirt

cd $NEORICALEX_HOME

