Vagrant.configure("2") do |config|
         config.vm.provider :libvirt do |libvirt|
         libvirt.driver = "kvm"
         libvirt.host = 'localhost'
         libvirt.uri = 'qemu:///system'
         end
config.vm.define "new" do |nfdos|
         nfdos.vm.box = "nfdos"       
         nfdos.vm.provider :libvirt do |nfdos|
         nfdos.memory = 1024
         nfdos.cpus = 1
         end
         end
end