#!/bin/sh

name=bulifs
error_prefix="[${name}] ERROR:"
scripts_dir=/usr/share/${name}

if [ -n "${SUDO_USER}" ]; then
	echo "${error_prefix} This script must be run without sudo."
	exit 1
fi

first_argument="${1}"
shift
case "${first_argument}" in
	config|build)
		[ "${first_argument}" = build ] && SUDO=sudo
		${SUDO} ${scripts_dir}/${name}_${first_argument} ${@}
		;;
	*)
		man ${name}
		;;
esac
