.TH bulifs 1 "November 2019" "1.1.1" "Build Ubuntu Live ISO From Scratch"

.SH NAME
bulifs

.SH SYNOPSIS
\fBbulifs\fP COMMAND [COMMAND_OPTIONS]

.SH DESCRIPTION
This is a tool to easily build a custom Ubuntu live ISO from scratch. It uses Debian's live-boot and live-config for the live system.

.SH COMMANDS
.IP "\fBconfig\fP" 4
creates live system configuration files, run this first.
.IP "\fBbuild\fP" 4
builds the ISO from the live system configuration files.

.SH BUGS
Report bugs and make feature requests on GitLab: <\fIhttps://gitlab.com/bfeber/bulifs/issues/new\fP>

.SH AUTHOR
Björn Feber (bfeber@protonmail.com)
