.TH bulifs\ config 1 "November 2019" "1.1.1" "Build Ubuntu Live ISO From Scratch"

.SH NAME
bulifs config

.SH SYNOPSIS
\fBbulifs config\fP

.SH DESCRIPTION
Creates live system configuration files, run this first.

.SH BUGS
Report bugs and make feature requests on GitLab: <\fIhttps://gitlab.com/bfeber/bulifs/issues/new\fP>

.SH AUTHOR
Björn Feber (bfeber@protonmail.com)
